export { buyCake } from './cake/cakeActions'
export { buyIceCream } from './iceCream/iceCreamActions'
export { buyOlive } from './olive/oliveActions'
export * from './user/userActions'
export * from './post/postActions'