export const SAVE_USER_TO_SERVER = 'SAVE_USER_TO_SERVER'
export const SAVE_USER_TO_SERVER_SUCCESS = 'SAVE_USER_TO_SERVER_SUCCESS'
export const SAVE_USER_TO_SERVER_FALIURE = 'SAVE_USER_TO_SERVER_FALIURE'